flowchart LR
    manifest[Manifest]
    
    subgraph ocb["OCB"]
        tmpl[Templates]
        code["Go<br>code"]
    end

    bin["fa:fa-terminal otelcol"]

    manifest --> tmpl
    tmpl --> code
    code -..->|"&nbsp;<code>go build</code>&nbsp;"| bin

class manifest,tmpl,code,bin box;
class manifest,tmpl,code,bin rounded;
class ocb container;
