flowchart LR
    manifest["manifest.yaml"]
    
    subgraph ocb["OCB"]
        tmpl["main.go.tmpl, ..."]
    end

    code["main.go, components.go, ..."]

    bin["fa:fa-terminal otelcol"]

    manifest --> ocb
    ocb --> code
    code -->|"&nbsp;go build&nbsp;"| bin

class manifest,tmpl,code,bin box;
class ocb container;
